
server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dat_bbms_db
  mail:
    host: smtp.gmail.com
    port: 587
    username: datofficial22@gmail.com
    password: fganjvbbbhjmsjyo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: qHcBipWQACWwXRNUjVgQSqqbBVfyfvIC

project:
  image: D:\fullstack_projects\ojt\ai-wms-backend\src\main\resources\static\img\
